CREATE TABLE Fornecedores(
  IdFornecedor INT NOT NULL AUTO_INCREMENT,
  RazaoSocial VARCHAR(60) NOT NULL,
  CNPJ VARCHAR(60) NOT NULL,
  PRIMARY KEY (IdFornecedor)
);

CREATE TABLE Produtos (
  IdProduto INT NOT NULL AUTO_INCREMENT,
  CodInterno INT NOT NULL,
  Descricao VARCHAR(100) NOT NULL,
  QuantMinVenda DOUBLE NOT NULL,
  CodBarras VARCHAR(30),
  Deposito DOUBLE NOT NULL,
  Estoque DOUBLE NOT NULL,
  Custo DOUBLE,
  CodFabricante VARCHAR(60),
  QuantCaixas INT,
  IdFornecedor INT NOT NULL,
  PRIMARY KEY (IdProduto),
  FOREIGN KEY (IdFornecedor) REFERENCES Fornecedores (IdFornecedor)
);

CREATE TABLE Ruas(
  IdRua INT NOT NULL AUTO_INCREMENT,
  NomeRua VARCHAR(60) NOT NULL,
  PRIMARY KEY (IdRua)
);

CREATE TABLE Predios (
  IdPredio INT NOT NULL AUTO_INCREMENT,
  NomePredio VARCHAR(60) NOT NULL,
  Vagas INT,
  IdRua INT NOT NULL,
  PRIMARY KEY (IdPredio),
  FOREIGN KEY (IdRua) REFERENCES Ruas (IdRua)
);

CREATE TABLE Listas (
  IdLista INT NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(20) NOT NULL,
  Disponivel BOOLEAN NOT NULL,
  PRIMARY KEY (IdLista)
);

CREATE TABLE Enderecamentos (
  IdEnderecamento INT NOT NULL AUTO_INCREMENT,
  Tonalidade VARCHAR(10) NOT NULL,
  Bitola VARCHAR(10) NOT NULL,
  Lote VARCHAR(30),
  Observacao VARCHAR(60),
  QuantCaixas INT,
  Disponivel BOOLEAN NOT NULL,
  IdProduto INT NOT NULL,
  IdLista INT,
  IdPredio INT NOT NULL,
  PRIMARY KEY (IdEnderecamento),
  FOREIGN KEY (IdProduto) REFERENCES Produtos (IdProduto),
  FOREIGN KEY (IdLista) REFERENCES Listas (IdLista),
  FOREIGN KEY (IdPredio) REFERENCES Predios (IdPredio)
);

CREATE TABLE Perfis (
  IdPerfil INT NOT NULL AUTO_INCREMENT,
  NomePerfil VARCHAR(60) NOT NULL,
  PRIMARY KEY (IdPerfil)
);

CREATE TABLE Usuarios (
  IdUsuario INT NOT NULL AUTO_INCREMENT,
  NomeCompleto VARCHAR(100) NOT NULL,
  Nickname VARCHAR(50) NOT NULL,
  Email VARCHAR(100) NOT NULL UNIQUE,
  Telefone VARCHAR(20),
  Senha VARCHAR(255) NOT NULL,
  Ativo BOOLEAN NOT NULL DEFAULT TRUE,
  IdPerfil INT NOT NULL,
  PRIMARY KEY (IdUsuario),
  FOREIGN KEY (IdPerfil) REFERENCES Perfis (IdPerfil)
);

CREATE TABLE Logs (
  IdLog INT NOT NULL AUTO_INCREMENT,
  IdUsuario INT NOT NULL,
  Entidade VARCHAR(20) NOT NULL,
  Acao VARCHAR(20) NOT NULL,
  Descricao VARCHAR(255) NOT NULL,
  DataHora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (IdLog),
  FOREIGN KEY (IdUsuario) REFERENCES Usuarios (IdUsuario)
);

